### ISSUE TITLE
Код не полностью рабочий

### ISSUE THREAD

**Issue by PsyPerception** [wb-08/opencv-tutorial#1]
Тестирую код, понимаю, что все сделано на совесть. Но то ли обновился cv, то ли не все учтено - ругается на функцию find_contours_of_cards, метод `cv2.CHAIN_APPROX_SIMPLE` ждет 3-х канальное изображение, а вы превращаете его в 2-х канальное через `gray_main_image = cv2.cvtColor(main_image, cv2.COLOR_BGR2GRAY)`, соответственно то, что дальше уже не будет работать.

**Comment by wb-08** [comment]
А какая версия OpenCV?

> Тестирую код, понимаю, что все сделано на совесть. Но то ли обновился cv, то ли не все учтено - ругается на функцию find_contours_of_cards, метод `cv2.CHAIN_APPROX_SIMPLE` ждет 3-х канальное изображение, а вы превращаете его в 2-х канальное через `gray_main_image = cv2.cvtColor(main_image, cv2.COLOR_BGR2GRAY)`, соответственно то, что дальше уже не будет работать.

**Comment by PsyPerception** [comment]
Уже понял, что дело в версии. Не ожидал, что за месяц поменяют что то в библиотеке. Ставил последнюю. Подскажите свою, на момент написания, пожалуйста.

**Comment by wb-08** [comment]
Это я просто старую использую:) У меня 3.4.2.17

**Comment by PsyPerception** [comment]
> Это я просто старую использую :) У меня 3.4.2.17

Вот спасибо. Было бы неплохо если бы Вы сделали файл requirements, на будущее.
